La_Palma:
	pdflatex La_Palma.tex
	pdflatex La_Palma.tex
	@rm -r La_Palma.aux La_Palma.bbl La_Palma.blg La_Palma.log La_Palma.out La_Palma.synctex.gz La_Palma.nav La_Palma.snm La_Palma.toc setup_La_Palma.log
